### ISSUE TITLE
이미지 처리 반환

### ISSUE THREAD

**Issue by leeseojune53** [DSM-FindApple/DSM-FindApple_Server#16]
https://github.com/DSM-FindApple/DSM-FindApple_Server/blob/9817c217197ffa2aa14bcaf458cd4c12bd7c7823/src/main/java/dsm/project/findapple/service/image/ImageServiceImpl.java#L39

위 코드를 보면 서버 로컬에 있는 image를 byte[]로 변환해서 return해주는데 이것 보다 nginx의 정적호스팅을 활용해서 server_addr/file_name 형식으로 반환해주는 것이 더 좋을거같아요

**Comment by yoct1994** [comment]
한번 알아보고 수정해보겠습니다. 피드백 감사합니다
